name: reviewdog
on: [push, pull_request]
jobs:
  vint:
    name: runner / mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: vint
        uses: kazukazuinaina/action-pyflakes@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
